FROM eclipse-temurin:21.0.11_10-jre-noble
WORKDIR /mc
# RUN apt-get install wget
# RUN wget https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
CMD java -Xmx4G -Xms4G -jar server.jar nogui